#!/bin/sh

# Copied from: https://github.com/akrabat/lambda-php/blob/2019-01-02-article/layer/php/bootstrap
# Itself modified from: https://github.com/pagnihotry/PHP-Lambda-Runtime/blob/master/runtime/bootstrap
# Copyright (c) 2018 Parikshit Agnihotry

# go into the source directory
cd $LAMBDA_TASK_ROOT

# execute the runtime
/opt/php /opt/runtime.php
